name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: pwd
      run: pwd zed
      
    - name: update
      run: git submodule update --init
      
    - name: Build Linux
      run: make apps-linux32
      
    - name: Build Win
      run: make apps-win
