name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: npm install
      
    - name: update
      run: git submodule update --init
      
    - name: Build Linux
      run: make apps-linux32
      
    - name: Build Win
      run: make apps-win
